// pending block contains data to be hashed
// all of the data in this block should be hashed for immutability purposes
unconfirmed_block: {
    header = {
        id: 0,
        previous_hash: "previous block's hash value",
        time_created: "time that block was created",
        created_by: "peer who created this block",
    },
    body = {
        data: "some data"
    }
}
// confirmed block contains more header data regarding confirmation
// can still be reconfirmed by taking all the data found in the unconfirmed block and hashing with the nonce
confirmed_block: {
    header = {
        id: 0,
        previous_hash: "previous block's hash value",
        time_created: "time that block was created",
        created_by: "peer who created this block",
        time_confirmed: "time that block was confirmed",
        confirmed_by: "peer who confirmed this block",
        nonce: 123456,
        hash: "hash value generated by the pending block + nonce"
    },
    body = {
        data: 0
    }
}